INSERT INTO characters (name, star, path, element, special, image_path) VALUES
                                                                            ('클라라', 'FIVE', '파멸', '물리', 'ALWAYS', '/images/character/FIVE/클라라.webp'),
                                                                             ('나타샤', 'FOUR', '풍요', '물리', 'ALWAYS', '/images/character/FOUR/나타샤.webp'),
                                                                             ('소상', 'FOUR', '수렵', '물리', 'ALWAYS', '/images/character/FOUR/소상.webp'),
                                                                             ('루카', 'FOUR', '공허', '물리', 'ALWAYS', '/images/character/FOUR/루카.webp'),
                                                                             ('아젠티', 'FIVE', '지식', '물리', 'SPECIAL', '/images/character/FIVE/아젠티.webp'),
                                                                             ('한아', 'FOUR', '화합', '물리', 'ALWAYS', '/images/character/FOUR/한아.webp'),
                                                                             ('로빈', 'FIVE', '화합', '물리', 'SPECIAL', '/images/character/FIVE/로빈.webp'),
                                                                             ('부트힐', 'FIVE', '수렵', '물리', 'SPECIAL', '/images/character/FIVE/부트힐.webp'),
                                                                             ('운리', 'FIVE', '파멸', '물리', 'SPECIAL', '/images/character/FIVE/운리.webp'),
                                                                             ('히메코', 'FIVE', '지식', '화염', 'ALWAYS', '/images/character/FIVE/히메코.webp'),
                                                                             ('아스타', 'FOUR', '화합', '화염', 'ALWAYS', '/images/character/FOUR/아스타.webp'),
                                                                             ('후크', 'FOUR', '파멸', '화염', 'ALWAYS', '/images/character/FOUR/후크.webp'),
                                                                             ('토파즈&복순이', 'FIVE', '수렵', '화염', 'SPECIAL', '/images/character/FIVE/토파즈&복순이.webp'),
                                                                             ('계네빈', 'FOUR', '공허', '화염', 'ALWAYS', '/images/character/FOUR/계네빈.webp'),
                                                                             ('갤러거', 'FOUR', '풍요', '화염', 'ALWAYS', '/images/character/FOUR/갤러거.webp'),
                                                                             ('반디', 'FIVE', '파멸', '화염', 'SPECIAL', '/images/character/FIVE/반디.webp'),
                                                                             ('초구', 'FIVE', '공허', '화염', 'SPECIAL', '/images/character/FIVE/초구.webp'),
                                                                             ('영사', 'FIVE', '풍요', '화염', 'SPECIAL', '/images/character/FIVE/영사.webp'),
                                                                             ('망귀인', 'FIVE', '공허', '화염', 'SPECIAL', '/images/character/FIVE/망귀인.webp'),
                                                                             ('게파드', 'FIVE', '보존', '얼음', 'ALWAYS', '/images/character/FIVE/게파드.webp'),
                                                                             ('연경', 'FIVE', '수렵', '얼음', 'ALWAYS', '/images/character/FIVE/연경.webp'),
                                                                             ('March_7th', 'FOUR', '보존', '얼음', 'ALWAYS', '/images/character/FOUR/March_7th.webp'),
                                                                             ('헤르타', 'FOUR', '지식', '얼음', 'ALWAYS', '/images/character/FOUR/헤르타.webp'),
                                                                             ('페라', 'FOUR', '공허', '얼음', 'ALWAYS', '/images/character/FOUR/페라.webp'),
                                                                             ('경류', 'FIVE', '파멸', '얼음', 'SPECIAL', '/images/character/FIVE/경류.webp'),
                                                                             ('완매', 'FIVE', '화합', '얼음', 'SPECIAL', '/images/character/FIVE/완매.webp'),
                                                                             ('미샤', 'FOUR', '파멸', '얼음', 'ALWAYS', '/images/character/FOUR/미샤.webp'),
                                                                             ('더 헤르타', 'FIVE', '지식', '얼음', 'SPECIAL', '/images/character/FIVE/더 헤르타.webp'),
                                                                             ('백로', 'FIVE', '풍요', '번개', 'ALWAYS', '/images/character/FIVE/백로.webp'),
                                                                             ('아를란', 'FOUR', '파멸', '번개', 'ALWAYS', '/images/character/FOUR/아를란.webp'),
                                                                             ('서벌', 'FOUR', '지식', '번개', 'ALWAYS', '/images/character/FOUR/서벌.webp'),
                                                                             ('정운', 'FOUR', '화합', '번개', 'ALWAYS', '/images/character/FOUR/정운.webp'),
                                                                             ('경원', 'FIVE', '지식', '번개', 'SPECIAL', '/images/character/FIVE/경원.webp'),
                                                                             ('카프카', 'FIVE', '공허', '번개', 'SPECIAL', '/images/character/FIVE/카프카.webp'),
                                                                             ('아케론', 'FIVE', '공허', '번개', 'SPECIAL', '/images/character/FIVE/아케론.webp'),
                                                                             ('맥택', 'FOUR', '수렵', '번개', 'ALWAYS', '/images/character/FOUR/맥택.webp'),
                                                                             ('아글라이아', 'FIVE', '기억', '번개', 'SPECIAL', '/images/character/FIVE/아글라이아.webp'),
                                                                             ('브로냐', 'FIVE', '화합', '바람', 'ALWAYS', '/images/character/FIVE/브로냐.webp'),
                                                                             ('단항', 'FOUR', '수렵', '바람', 'ALWAYS', '/images/character/FOUR/단항.webp'),
                                                                             ('삼포', 'FOUR', '공허', '바람', 'ALWAYS', '/images/character/FOUR/삼포.webp'),
                                                                             ('블레이드', 'FIVE', '파멸', '바람', 'SPECIAL', '/images/character/FIVE/블레이드.webp'),
                                                                             ('곽향', 'FIVE', '풍요', '바람', 'SPECIAL', '/images/character/FIVE/곽향.webp'),
                                                                             ('블랙스완', 'FIVE', '공허', '바람', 'SPECIAL', '/images/character/FIVE/블랙스완.webp'),
                                                                             ('비소', 'FIVE', '수렵', '바람', 'SPECIAL', '/images/character/FIVE/비소.webp'),
                                                                             ('청작', 'FOUR', '지식', '양자', 'ALWAYS', '/images/character/FOUR/청작.webp'),
                                                                             ('제레', 'FIVE', '수렵', '양자', 'SPECIAL', '/images/character/FIVE/제레.webp'),
                                                                             ('은랑', 'FIVE', '공허', '양자', 'SPECIAL', '/images/character/FIVE/은랑.webp'),
                                                                             ('부현', 'FIVE', '보존', '양자', 'SPECIAL', '/images/character/FIVE/부현.webp'),
                                                                             ('링스', 'FOUR', '풍요', '양자', 'ALWAYS', '/images/character/FOUR/링스.webp'),
                                                                             ('설의', 'FOUR', '파멸', '양자', 'ALWAYS', '/images/character/FOUR/설의.webp'),
                                                                             ('스파클', 'FIVE', '화합', '양자', 'SPECIAL', '/images/character/FIVE/스파클.webp'),
                                                                             ('제이드', 'FIVE', '지식', '양자', 'SPECIAL', '/images/character/FIVE/제이드.webp'),
                                                                             ('웰트', 'FIVE', '공허', '허수', 'ALWAYS', '/images/character/FIVE/웰트.webp'),
                                                                             ('나찰', 'FIVE', '풍요', '허수', 'SPECIAL', '/images/character/FIVE/나찰.webp'),
                                                                             ('어공', 'FOUR', '화합', '허수', 'ALWAYS', '/images/character/FOUR/어공.webp'),
                                                                             ('단항·음월', 'FIVE', '파멸', '허수', 'SPECIAL', '/images/character/FIVE/단항·음월.webp'),
                                                                             ('Dr_레이시오', 'FIVE', '수렵', '허수', 'SPECIAL', '/images/character/FIVE/Dr_레이시오.webp'),
                                                                             ('어벤츄린', 'FIVE', '보존', '허수', 'SPECIAL', '/images/character/FIVE/어벤츄린.webp'),
                                                                             ('라파', 'FIVE', '지식', '허수', 'SPECIAL', '/images/character/FIVE/라파.webp'),
                                                                             ('선데이', 'FIVE', '화합', '허수', 'SPECIAL', '/images/character/FIVE/선데이.webp'),
                                                                            ('썸네일', 'FIVE', '화합', '허수', 'SPECIAL', '/images/character/character_thumbnail.png')
    ON DUPLICATE KEY UPDATE star = VALUES(star), path = VALUES(path), element = VALUES(element), special = VALUES(special), image_path = VALUES(image_path);
INSERT INTO lightcones (name, star, path, special, image_path) VALUES
                                                                     ('대체할 수 없는 것', 'FIVE', '파멸', 'ALWAYS', '/images/lightCone/FIVE/대체할 수 없는 것.png'),
                                                                     ('닿을 수 없는 저편', 'FIVE', '파멸', 'SPECIAL', '/images/lightCone/FIVE/닿을 수 없는 저편.png'),
                                                                     ('태양보다 밝게 빛나는 것', 'FIVE', '파멸', 'SPECIAL', '/images/lightCone/FIVE/태양보다 밝게 빛나는 것.png'),
                                                                     ('이 몸이 검이니', 'FIVE', '파멸', 'SPECIAL', '/images/lightCone/FIVE/이 몸이 검이니.png'),
                                                                     ('꿈은 어디로 돌아가야 하는가', 'FIVE', '파멸', 'SPECIAL', '/images/lightCone/FIVE/꿈은 어디로 돌아가야 하는가.png'),
                                                                     ('해 질 무렵 시작되는 춤', 'FIVE', '파멸', 'SPECIAL', '/images/lightCone/FIVE/해 질 무렵 시작되는 춤.png'),
                                                                     ('두더지파가 환영해', 'FOUR', '파멸', 'ALWAYS', '/images/lightCone/FOUR/두더지파가 환영해.png'),
                                                                     ('비밀 맹세', 'FOUR', '파멸', 'ALWAYS', '/images/lightCone/FOUR/비밀 맹세.png'),
                                                                     ('푸른 하늘 아래', 'FOUR', '파멸', 'ALWAYS', '/images/lightCone/FOUR/푸른 하늘 아래.png'),
                                                                     ('마음에 새긴 약속', 'FOUR', '파멸', 'ALWAYS', '/images/lightCone/FOUR/마음에 새긴 약속.png'),
                                                                     ('천경', 'THREE', '파멸', 'ALWAYS', '/images/lightCone/THREE/천경.png'),
                                                                     ('무너진 행복', 'THREE', '파멸', 'ALWAYS', '/images/lightCone/THREE/무너진 행복.png'),
                                                                     ('전멸', 'THREE', '파멸', 'ALWAYS', '/images/lightCone/THREE/전멸.png'),
                                                                     ('깊게 든 단잠', 'FIVE', '수렵', 'ALWAYS', '/images/lightCone/FIVE/깊게 든 단잠.png'),
                                                                     ('야경 속에서', 'FIVE', '수렵', 'SPECIAL', '/images/lightCone/FIVE/야경 속에서.png'),
                                                                     ('고민, 그리고 행복', 'FIVE', '수렵', 'SPECIAL', '/images/lightCone/FIVE/고민, 그리고 행복.png'),
                                                                     ('순수 사유의 세례', 'FIVE', '수렵', 'SPECIAL', '/images/lightCone/FIVE/순수 사유의 세례.png'),
                                                                     ('두 번째 생명을 향해', 'FIVE', '수렵', 'SPECIAL', '/images/lightCone/FIVE/두 번째 생명을 향해.png'),
                                                                     ('정복하고 사냥하리', 'FIVE', '수렵', 'SPECIAL', '/images/lightCone/FIVE/정복하고 사냥하리.png'),
                                                                     ('침묵만이', 'FOUR', '수렵', 'ALWAYS', '/images/lightCone/FOUR/침묵만이.png'),
                                                                     ('논검', 'FOUR', '수렵', 'ALWAYS', '/images/lightCone/FOUR/논검.png'),
                                                                     ('팔로우를 부탁해!', 'FOUR', '수렵', 'ALWAYS', '/images/lightCone/FOUR/팔로우를 부탁해!.png'),
                                                                     ('그림자처럼 뒤따르는 밤', 'FOUR', '수렵', 'ALWAYS', '/images/lightCone/FOUR/그림자처럼 뒤따르는 밤.png'),
                                                                     ('화살촉', 'THREE', '수렵', 'ALWAYS', '/images/lightCone/THREE/화살촉.png'),
                                                                     ('시위를 떠난 화살', 'THREE', '수렵', 'ALWAYS', '/images/lightCone/THREE/시위를 떠난 화살.png'),
                                                                     ('대립', 'THREE', '수렵', 'ALWAYS', '/images/lightCone/THREE/대립.png'),
                                                                     ('은하철도의 밤', 'FIVE', '지식', 'ALWAYS', '/images/lightCone/FIVE/은하철도의 밤.png'),
                                                                     ('추궁할 수 없는 곳을 향해', 'FIVE', '지식', 'SPECIAL', '/images/lightCone/FIVE/추궁할 수 없는 곳을 향해.png'),
                                                                     ('동트기 전', 'FIVE', '지식', 'SPECIAL', '/images/lightCone/FIVE/동트기 전.png'),
                                                                     ('눈에 담긴 순간', 'FIVE', '지식', 'SPECIAL', '/images/lightCone/FIVE/눈에 담긴 순간.png'),
                                                                     ('값을 매길 수 없는 건 희망뿐', 'FIVE', '지식', 'SPECIAL', '/images/lightCone/FIVE/값을 매길 수 없는 건 희망뿐.png'),
                                                                     ('인법첩·요란 파마', 'FIVE', '지식', 'SPECIAL', '/images/lightCone/FIVE/인법첩·요란 파마.png'),
                                                                     ('「나」의 탄생', 'FOUR', '지식', 'ALWAYS', '/images/lightCone/FOUR/「나」의 탄생.png'),
                                                                     ('세상을 진정시키지 마', 'FOUR', '지식', 'ALWAYS', '/images/lightCone/FOUR/세상을 진정시키지 마.png'),
                                                                     ('천재들의 휴식', 'FOUR', '지식', 'ALWAYS', '/images/lightCone/FOUR/천재들의 휴식.png'),
                                                                     ('조화가 침묵한 후', 'FOUR', '지식', 'ALWAYS', '/images/lightCone/FOUR/조화가 침묵한 후.png'),
                                                                     ('아카이브', 'THREE', '지식', 'ALWAYS', '/images/lightCone/THREE/아카이브.png'),
                                                                     ('영험한 열쇠', 'THREE', '지식', 'ALWAYS', '/images/lightCone/THREE/영험한 열쇠.png'),
                                                                     ('식견', 'THREE', '지식', 'ALWAYS', '/images/lightCone/THREE/식견.png'),
                                                                     ('아직 전투는 끝나지 않았다', 'FIVE', '화합', 'ALWAYS', '/images/lightCone/FIVE/아직 전투는 끝나지 않았다.png'),
                                                                     ('거울 속 지난날의 나', 'FIVE', '화합', 'SPECIAL', '/images/lightCone/FIVE/거울 속 지난날의 나.png'),
                                                                     ('속세에서의 유희', 'FIVE', '화합', 'SPECIAL', '/images/lightCone/FIVE/속세에서의 유희.png'),
                                                                     ('찬란하게 빛나는 밤', 'FIVE', '화합', 'SPECIAL', '/images/lightCone/FIVE/찬란하게 빛나는 밤.png'),
                                                                     ('대지로 돌아온 비행', 'FIVE', '화합', 'SPECIAL', '/images/lightCone/FIVE/대지로 돌아온 비행.png'),
                                                                     ('기억 속 모습', 'FOUR', '화합', 'ALWAYS', '/images/lightCone/FOUR/기억 속 모습.png'),
                                                                     ('행성과의 만남', 'FOUR', '화합', 'ALWAYS', '/images/lightCone/FOUR/행성과의 만남.png'),
                                                                     ('댄스! 댄스! 댄스!', 'FOUR', '화합', 'ALWAYS', '/images/lightCone/FOUR/댄스! 댄스! 댄스!.png'),
                                                                     ('피어나길 기다리는 꽃', 'FOUR', '화합', 'ALWAYS', '/images/lightCone/FOUR/피어나길 기다리는 꽃.png'),
                                                                     ('합창', 'THREE', '화합', 'ALWAYS', '/images/lightCone/THREE/합창.png'),
                                                                     ('맞물린 톱니', 'THREE', '화합', 'ALWAYS', '/images/lightCone/THREE/맞물린 톱니.png'),
                                                                     ('어울림', 'THREE', '화합', 'ALWAYS', '/images/lightCone/THREE/어울림.png'),
                                                                     ('세계의 이름으로', 'FIVE', '공허', 'ALWAYS', '/images/lightCone/FIVE/세계의 이름으로.png'),
                                                                     ('계속 내리는 비', 'FIVE', '공허', 'SPECIAL', '/images/lightCone/FIVE/계속 내리는 비.png'),
                                                                     ('필요한 건 기다림뿐', 'FIVE', '공허', 'SPECIAL', '/images/lightCone/FIVE/필요한 건 기다림뿐.png'),
                                                                     ('시간의 기억에 대한 재구성', 'FIVE', '공허', 'SPECIAL', '/images/lightCone/FIVE/시간의 기억에 대한 재구성.png'),
                                                                     ('흘러가는 강가를 따라', 'FIVE', '공허', 'SPECIAL', '/images/lightCone/FIVE/흘러가는 강가를 따라.png'),
                                                                     ('그 무수한 봄날', 'FIVE', '공허', 'SPECIAL', '/images/lightCone/FIVE/그 무수한 봄날.png'),
                                                                     ('먼 길 끝의 귀로', 'FIVE', '공허', 'SPECIAL', '/images/lightCone/FIVE/먼 길 끝의 귀로.png'),
                                                                     ('밤 인사와 잠든 얼굴', 'FOUR', '공허', 'ALWAYS', '/images/lightCone/FOUR/밤 인사와 잠든 얼굴.png'),
                                                                     ('사냥감의 시선', 'FOUR', '공허', 'ALWAYS', '/images/lightCone/FOUR/사냥감의 시선.png'),
                                                                     ('땀방울처럼 빛나는 결심', 'FOUR', '공허', 'ALWAYS', '/images/lightCone/FOUR/땀방울처럼 빛나는 결심.png'),
                                                                     ('끝없는 춤', 'FOUR', '공허', 'ALWAYS', '/images/lightCone/FOUR/끝없는 춤.png'),
                                                                     ('그윽', 'THREE', '공허', 'ALWAYS', '/images/lightCone/THREE/그윽.png'),
                                                                     ('심연의 고리', 'THREE', '공허', 'ALWAYS', '/images/lightCone/THREE/심연의 고리.png'),
                                                                     ('숨은 그림자', 'THREE', '공허', 'ALWAYS', '/images/lightCone/THREE/숨은 그림자.png'),
                                                                     ('승리의 순간', 'FIVE', '보존', 'ALWAYS', '/images/lightCone/FIVE/승리의 순간.png'),
                                                                     ('그녀는 두 눈을 감았네', 'FIVE', '보존', 'SPECIAL', '/images/lightCone/FIVE/그녀는 두 눈을 감았네.png'),
                                                                     ('언제나 불공평한 운명', 'FIVE', '보존', 'SPECIAL', '/images/lightCone/FIVE/언제나 불공평한 운명.png'),
                                                                     ('여생의 첫날', 'FOUR', '보존', 'ALWAYS', '/images/lightCone/FOUR/여생의 첫날.png'),
                                                                     ('랜도의 선택', 'FOUR', '보존', 'ALWAYS', '/images/lightCone/FOUR/랜도의 선택.png'),
                                                                     ('우주 시장 동향', 'FOUR', '보존', 'ALWAYS', '/images/lightCone/FOUR/우주 시장 동향.png'),
                                                                     ('두 사람의 콘서트', 'FOUR', '보존', 'ALWAYS', '/images/lightCone/FOUR/두 사람의 콘서트.png'),
                                                                     ('수비', 'THREE', '보존', 'ALWAYS', '/images/lightCone/THREE/수비.png'),
                                                                     ('앰버', 'THREE', '보존', 'ALWAYS', '/images/lightCone/THREE/앰버.png'),
                                                                     ('강토 개척', 'THREE', '보존', 'ALWAYS', '/images/lightCone/THREE/강토 개척.png'),
                                                                     ('세월은 흐를 뿐', 'FIVE', '풍요', 'ALWAYS', '/images/lightCone/FIVE/세월은 흐를 뿐.png'),
                                                                     ('관의 울림', 'FIVE', '풍요', 'SPECIAL', '/images/lightCone/FIVE/관의 울림.png'),
                                                                     ('섬뜩한 밤', 'FIVE', '풍요', 'SPECIAL', '/images/lightCone/FIVE/섬뜩한 밤.png'),
                                                                     ('오직 향만이 변함없이', 'FIVE', '풍요', 'SPECIAL', '/images/lightCone/FIVE/오직 향만이 변함없이.png'),
                                                                     ('수술 후의 대화', 'FOUR', '풍요', 'ALWAYS', '/images/lightCone/FOUR/수술 후의 대화.png'),
                                                                     ('같은 심정', 'FOUR', '풍요', 'ALWAYS', '/images/lightCone/FOUR/같은 심정.png'),
                                                                     ('알맞은 타이밍', 'FOUR', '풍요', 'ALWAYS', '/images/lightCone/FOUR/알맞은 타이밍.png'),
                                                                     ('꿈의 몽타주', 'FOUR', '풍요', 'ALWAYS', '/images/lightCone/FOUR/꿈의 몽타주.png'),
                                                                     ('풍작', 'THREE', '풍요', 'ALWAYS', '/images/lightCone/THREE/풍작.png'),
                                                                     ('알찬 열매', 'THREE', '풍요', 'ALWAYS', '/images/lightCone/THREE/알찬 열매.png'),
                                                                     ('증식', 'THREE', '풍요', 'ALWAYS', '/images/lightCone/THREE/증식.png')
    ON DUPLICATE KEY UPDATE star = VALUES(star), path = VALUES(path), special = VALUES(special), image_path = VALUES(image_path);